export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];


export const stateAreas = {
  "Andhra Pradesh": {
    "Anantapur": [
      "Anantapur",
      "Kalyandurg",
      "Kadiri",
      "Rayadurg",
      "Uravakonda",
      "Guntakal",
      "Tadipatri",
      "Hindupur",
      "Penukonda",
      "Dharmavaram"
    ],
    "Chittoor": [
      "Chittoor",
      "Tirupati Urban",
      "Tirupati Rural",
      "Madanapalle",
      "Punganur",
      "Nagari",
      "Srikalahasti",
      "Palamaner",
      "Bangarupalem",
      "Kuppam"
    ],
    "East Godavari": [
      "Rajahmundry Urban",
      "Rajahmundry Rural",
      "Kakinada Urban",
      "Kakinada Rural",
      "Amalapuram",
      "Ramachandrapuram",
      "Peddapuram",
      "Mandapeta",
      "Tuni",
      "Ravulapalem"
    ],
    "Eluru": [
      "Bhimadole",
      "Denduluru",
      "Eluru",
      "Kaikalur",
      "Kalidindi",
      "Mandavalli",
      "Mudinepalle",
      "Nidamarru",
      "Pedapadu",
      "Pedavegi",
      "Unguturu",
      "Buttayagudem",
      "Dwaraka Tirumala",
      "Jangareddygudem",
      "Jeelugu Milli",
      "Kamavarapukota",
      "Koyyalagudem",
      "Polavaram",
      "T.Narasapuram"
    ],
    "Guntur": [
      "Amaravathi",
      "Atchampet",
      "Bellamkonda",
      "Bollapalle",
      "Chebrolu",
      "Dachepalle",
      "Duggirala",
      "Guntur East",
      "Guntur West",
      "Ipur",
      "Karlapalem",
      "Kollipara",
      "Krosuru",
      "Macherla",
      "Machavaram",
      "Mangalagiri",
      "Medikonduru",
      "Narasaraopet",
      "Nadendla",
      "Nekarikallu",
      "Pedakakani",
      "Pedanandipadu",
      "Phirangipuram",
      "Ponnur",
      "Prathipadu",
      "Rajupalem",
      "Repalle",
      "Rentachintala",
      "Sattenapalle",
      "Savalyapuram",
      "Tadikonda",
      "Tenali",
      "Thullur",
      "Tsundur",
      "Vatticherukuru",
      "Veldurthi",
      "Vinukonda"
    ],
    "Kakinada": [
      "Kakinada Urban",
      "Kakinada Rural",
      "Samalkota",
      "Peddapuram",
      "Pithapuram",
      "Jaggampeta",
      "Tuni",
      "Thondangi",
      "Yeleswaram",
      "Kirlampudi",
      "Gollaprolu",
      "Rowthulapudi",
      "Sankhavaram",
      "Prathipadu",
      "Gandepalli"
    ],
    "Krishna": [
      "Gudivada",
      "Kaikaluru",
      "Machilipatnam",
      "Pamarru",
      "Vuyyuru",
      "Movva",
      "Avanigadda",
      "Koduru",
      "Pedana",
      "Nandivada",
      "Gudlavalleru",
      "Bantumilli",
      "Kruthivennu",
      "Nagayalanka"
    ],
    "Kurnool": [
      "Adoni",
      "Alur",
      "Aspari",
      "C. Belagal",
      "Chippagiri",
      "Devanakonda",
      "Dhone",
      "Gonegandla",
      "Gudur",
      "Halaharvi",
      "Holagunda",
      "Kodumur",
      "Kosigi",
      "Kowthalam",
      "Kurnool",
      "Krishnagiri",
      "Mantralayam",
      "Midthur",
      "Nandavaram",
      "Nandyal",
      "Nandikotkur",
      "Orvakal",
      "Panyam",
      "Pattikonda",
      "Peapully",
      "Sanjamala",
      "Srisailam",
      "Tuggali",
      "Uyyalawada",
      "Veldurthi",
      "Yemmiganur"
    ],
    "Nellore": [
      "Atmakur",
      "Anumasamudrampeta",
      "Bogole",
      "Buchireddypalem",
      "Chejerla",
      "Dagadarthi",
      "Dakkili",
      "Gudur",
      "Indukurpet",
      "Jaladanki",
      "Kaligiri",
      "Kavali",
      "Kodavalur",
      "Kondapuram",
      "Manubolu",
      "Muthukur",
      "Nellore",
      "Podalakur",
      "Rapur",
      "Saidapuram",
      "Sangam",
      "Seetharamapuram",
      "Sri Avadutha Kasinayana",
      "Tada",
      "Thotapalligudur",
      "Udayagiri",
      "Varikuntapadu",
      "Venkatagiri",
      "Vidavalur",
      "Vinjamur"
    ],
    "Prakasam": [
      "Addanki",
      "Ballikurava",
      "Chimakurthy",
      "Darsi",
      "Donakonda",
      "Giddalur",
      "Inkollu",
      "Kanigiri",
      "Kondapi",
      "Kurichedu",
      "Korisapadu",
      "Maddipadu",
      "Markapuram",
      "Mundlamuru",
      "Naguluppalapadu",
      "Ongole",
      "Parchur",
      "Podili",
      "Santhamaguluru",
      "Tangutur",
      "Tarlupadu",
      "Tripuranthakam",
      "Veligandla",
      "Vetapalem",
      "Yerragondapalem",
      "Zarugumilli"
    ]
  }
};
